name: main
on: 
- push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-node@v3
    - run: git clone --depth=1 https://github.com/mugiseyebrows/cicd-shell.git
    - run: |
        pushd cicd-shell\server
        npm i
        node index.js shell.hec.to 8857
        popd
      shell: cmd
