name: main
on: 
- push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: mugiseyebrows/cicd-shell-server@v1.1
      with:
        host: shell.hec.to
        port: 8857
        secret: ${{ secrets.SERVER_SECRET }}